##
# Whether to deploy sylva-core
#
deploy_sylva_core: false
sylva_core_repo_url: https://gitlab.com/codefol/sylva-core.git
sylva_core_branch: metal3_existing_rancher
baremetal_repo_url: https://github.com/suse-edge/charts.git
baremetal_branch: main

# VM user name
vm_user: metal

# VM user plain text password (not hash)
vm_user_plain_text_password: metal

# NOTE: this should be *your* (local user) SSH public key since *you*
# will be using it to login to the VMs. The SSH public keys listed
# here will be appended to the VM user's authorized_keys file.
#
vm_authorized_ssh_keys:
 -YOU CAN REPLACE THIS BUT THE SCRIPT WILL CHANGE THIS AUTOMATICALLY 

# OS image
opensuse_leap_image_url: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.5/images/openSUSE-Leap-15.5.x86_64-NoCloud.qcow2
opensuse_leap_image_checksum: sha256:https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.5/images/openSUSE-Leap-15.5.x86_64-NoCloud.qcow2.sha256
opensuse_leap_image_name: openSUSE-Leap-15.5.x86_64-NoCloud.qcow2

rke2_channel_version: v1.24

dns_domain: suse.baremetal


metal3_provisioning_nic: &metal3_provisioning_nic eth1


metal3_vm_libvirt_network_params: '--network bridge=m3-egress,model=virtio --network bridge=m3-prov,model=virtio'


metal3_network_infra_provisioning_ip: 192.168.124.100
vm_prov_gw: 192.168.124.1
vm_prov_net: 192.168.124.0/24


metal3_network_infra_public_ip: 192.168.125.100
vm_egress_gw: 192.168.125.1


enable_dhcp: true


dhcp_router: 192.168.124.1
dhcp_range: 192.168.124.150,192.168.124.180

metal3_network_infra_vm_network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses: ["{{ metal3_core_public_ip }}/24"]
      nameservers:
        addresses: "{{ vm_egress_gw }}"
      routes:
        - to: default
          via: "{{ vm_egress_gw }}"
    *metal3_provisioning_nic:
      dhcp4: false
      addresses: ["{{ metal3_core_provisioning_ip }}/24"]
      nameservers:
        addresses: "{{ vm_prov_gw }}"
      routes:
        - to: "{{ vm_prov_net }}"
          via: "{{ vm_prov_gw }}"


metal3_core_provisioning_ip: 192.168.124.99

#
# Public IP
#
metal3_core_public_ip: 192.168.125.99


metal3_core_vm_network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses: ["{{ metal3_core_public_ip }}/24"]
      nameservers:
        addresses: "{{ vm_egress_gw }}"
      routes:
        - to: default
          via: "{{ vm_egress_gw }}"
    *metal3_provisioning_nic:
      dhcp4: false
      addresses: ["{{ metal3_core_provisioning_ip }}/24"]
      nameservers:
        addresses: "{{ vm_prov_gw }}"
      routes:
        - to: "{{ vm_prov_net }}"
          via: "{{ vm_prov_gw }}"
