---
# see https://docs.rke2.io/install/quickstart/
rke2_installer_url: https://get.rke2.io

# rke2 channel version to install
# see https://update.rke2.io/v1-release/channels for a complete list
#
# i.e. 'v1.24'
rke2_channel_version: v1.24
