---
- name: Define metal3-core node
  hosts: localhost
  gather_facts: False
  tasks:
    
      
    - name: Add new host
      delegate_to: localhost
      ansible.builtin.add_host:
        name: "metal3-core"
        hostname: "metal3-core"
        groups: "{{ metal3_corehost_group | default('metal3_core_group') }}"
        ansible_python_interpreter: "{{ vm_python_interpreter | default('/usr/bin/python3') }}"
        ansible_user: "metal"
        ansible_host: "192.168.125.99"

- name: Tasks on new host
  hosts: metal3-core
  tasks:
  
    - name: Installing Python dependency
      become: yes
      ansible.builtin.zypper:
        name: python310-dbm
        state: present
        
    - name: Copy node1 yaml over
      copy: 
        src: "{{ VBMCDIR }}/node1.yaml"
        dest: /home/metal/node1.yaml
        
    - name: Copy node2 yaml over
      copy: 
        src: "{{ VBMCDIR }}/node2.yaml"
        dest: /home/metal/node2.yaml
        
    - name: Copy node3 yaml over
      copy: 
        src: "{{ VBMCDIR }}/node3.yaml"
        dest: /home/metal/node3.yaml
        
    - name: Create first bmh
      shell: kubectl apply -f node1.yaml
      
    - name: Create second bmh
      shell: kubectl apply -f node2.yaml
      
    - name: Create third bmh
      shell: kubectl apply -f node3.yaml