---
cert_manager_helm_repo_name: jetstack
cert_manager_helm_repo_url: https://charts.jetstack.io
cert_manager_helm_chart_ref: jetstack/cert-manager

cert_manager_namespace: cert-manager
cert_manager_release: cert-manager
